# Generated by Django 4.2.14 on 2024-08-05 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warcraft', '0002_background'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characters',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='characters',
            name='video',
        ),
    ]
